# -*- coding: utf-8 -*-
"""
OSLC Godaun Shelf Barcode Print Software
DigiBizz Direct PDF Re-Assembler (PyMuPDF) & ReportLab Generator
"""
import io
import re
import base64
from typing import List, Dict, Any, Optional

import pymupdf
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.graphics.barcode import code128
from reportlab.lib import colors

from apps.barcode.backend.db import natural_sort_key


def parse_digibizz_pdf_with_thumbnails(file_source, dpi: int = 200) -> List[Dict[str, Any]]:
    """
    Reads a PDF exported from DigiBizz (which has 1 barcode per page),
    extracts the exact label text, extracts thumbnail image of the original DigiBizz barcode,
    and sorts them in strict natural sequential order (1, 2, 3... AAA1, AAA2... F447, F448...).
    """
    if isinstance(file_source, bytes):
        doc = pymupdf.open(stream=file_source, filetype="pdf")
    else:
        doc = pymupdf.open(file_source)

    extracted = []
    for pno in range(len(doc)):
        page = doc[pno]
        raw_text = page.get_text() or ""
        txt = raw_text.strip().replace('\n', ' ')

        # Pattern: e.g. F548-(Rack : F1) or AAA701-(Rack : AAA01)
        m = re.search(r'([A-Za-z0-9]+)\s*-\s*\(\s*Rack\s*:\s*([^)]*)\)', txt, re.I)
        if m:
            shelf = m.group(1).strip()
            rack = m.group(2).strip()
        else:
            m2 = re.search(r'([A-Za-z0-9]+)', txt)
            shelf = m2.group(1).strip() if m2 else f"PAGE_{pno+1}"
            rack = ""

        # Extract number for range filtering
        num_match = re.search(r'(\d+)', shelf)
        item_num = int(num_match.group(1)) if num_match else 0

        # Render high-resolution thumbnail of the exact DigiBizz label
        pix = page.get_pixmap(dpi=dpi)
        img_bytes = pix.tobytes("png")
        b64 = base64.b64encode(img_bytes).decode("utf-8")

        extracted.append({
            "pno": pno,
            "shelf": shelf,
            "rack": rack,
            "full_text": txt if txt else shelf,
            "thumbnail_b64": b64,
            "num": item_num,
            "is_digi_source": True
        })

    # Sort strictly in natural continuous linear order: 1, 2, 3... F447..F550
    extracted.sort(key=lambda x: natural_sort_key(x["shelf"]))
    return extracted


def assemble_digibizz_pdf_to_a4(
    file_source,
    items_to_print: Optional[List[Dict[str, Any]]] = None,
    layout_type: str = "2x10",       # "2x10" (20/page) or "2x5" (10/page)
    order_direction: str = "row",    # "row" (1,2 / 3,4) or "col" (1-10 left, 11-20 right)
    show_border: bool = True
) -> bytes:
    """
    Takes the original DigiBizz PDF, selects the requested barcode pages,
    and places them directly into an A4 page with EXACTLY 20 barcodes per page (2 columns x 10 rows),
    keeping the EXACT vector barcode, fonts, and layout generated by DigiBizz!
    """
    if isinstance(file_source, bytes):
        src_doc = pymupdf.open(stream=file_source, filetype="pdf")
    else:
        src_doc = pymupdf.open(file_source)

    if items_to_print is None:
        items_to_print = parse_digibizz_pdf_with_thumbnails(file_source, dpi=72)

    out_doc = pymupdf.open()
    a4_w, a4_h = 595.28, 841.89  # A4 size in points

    if layout_type == "2x10":
        cols = 2
        rows = 10
    else:
        cols = 2
        rows = 5

    per_page = cols * rows
    margin_x = 20.0
    margin_y = 20.0
    cell_w = (a4_w - 2 * margin_x) / cols
    cell_h = (a4_h - 2 * margin_y) / rows

    total_pages = (len(items_to_print) + per_page - 1) // per_page if items_to_print else 1

    for p in range(total_pages):
        new_page = out_doc.new_page(width=a4_w, height=a4_h)
        chunk = items_to_print[p * per_page : (p + 1) * per_page]

        # Order arrangement: row-wise or col-wise
        if cols == 2 and order_direction == "col":
            display_items = [None] * per_page
            left_half = chunk[:rows]
            right_half = chunk[rows:rows * 2]
            for r_idx in range(rows):
                if r_idx < len(left_half):
                    display_items[r_idx * cols + 0] = left_half[r_idx]
                if r_idx < len(right_half):
                    display_items[r_idx * cols + 1] = right_half[r_idx]
        else:
            display_items = chunk

        for idx, it in enumerate(display_items):
            if not it:
                continue

            r = idx // cols
            c = idx % cols

            x0 = margin_x + c * cell_w + 5.0
            y0 = margin_y + r * cell_h + 2.0
            x1 = x0 + cell_w - 10.0
            y1 = y0 + cell_h - 4.0
            target_rect = pymupdf.Rect(x0, y0, x1, y1)

            # Place original DigiBizz vector page directly!
            src_pno = it.get("pno", 0)
            if 0 <= src_pno < len(src_doc):
                new_page.show_pdf_page(target_rect, src_doc, src_pno)

            # Optional cutting guidelines
            if show_border:
                border_rect = pymupdf.Rect(
                    margin_x + c * cell_w,
                    margin_y + r * cell_h,
                    margin_x + (c + 1) * cell_w,
                    margin_y + (r + 1) * cell_h
                )
                new_page.draw_rect(border_rect, color=(0.82, 0.84, 0.86), width=0.5, dashes='[3 3]')

    out_bytes = out_doc.tobytes()
    out_doc.close()
    src_doc.close()
    return out_bytes


def generate_a4_barcode_pdf(
    items: List[Dict[str, Any]],
    layout_type: str = "2x10",       # "2x10" (20/page - default) or "2x5" (10/page)
    order_direction: str = "row",    # "row" (1,2 / 3,4) or "col" (1-10 left, 11-20 right)
    show_border: bool = True,
    show_rack: bool = True,
    barcode_height: float = 28.0,
    barcode_scale: float = 1.05,
    font_size: float = 10.0
) -> bytes:
    """
    ReportLab vector generator for programmatic barcode ranges (20 per page by default).
    """
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    page_w, page_h = A4

    if layout_type == "2x10":
        cols = 2
        rows = 10
        label_w = 260.0
        label_h = 72.0
        margin_x = 28.35
        margin_y = 28.35
        gap_x = (page_w - 2 * margin_x - cols * label_w) / max(1, cols - 1)
        gap_y = (page_h - 2 * margin_y - rows * label_h) / max(1, rows - 1)
    elif layout_type == "1x10":
        cols = 1
        rows = 10
        label_w = 538.58
        label_h = 74.0
        margin_x = 28.35
        margin_y = 28.35
        gap_x = 0
        gap_y = (page_h - 2 * margin_y - rows * label_h) / max(1, rows - 1)
    else:
        cols = 2
        rows = 5
        label_w = 260.0
        label_h = 150.0
        margin_x = 28.35
        margin_y = 28.35
        gap_x = (page_w - 2 * margin_x - cols * label_w) / max(1, cols - 1)
        gap_y = (page_h - 2 * margin_y - rows * label_h) / max(1, rows - 1)

    per_page = cols * rows
    total_pages = (len(items) + per_page - 1) // per_page if items else 1

    for p in range(total_pages):
        chunk = items[p * per_page : (p + 1) * per_page]

        if cols == 2 and order_direction == "col":
            page_items = [None] * per_page
            left_half = chunk[:rows]
            right_half = chunk[rows:rows * 2]
            for r_idx in range(rows):
                if r_idx < len(left_half):
                    page_items[r_idx * cols + 0] = left_half[r_idx]
                if r_idx < len(right_half):
                    page_items[r_idx * cols + 1] = right_half[r_idx]
        else:
            page_items = chunk

        for idx, item in enumerate(page_items):
            if not item:
                continue

            row = idx // cols
            col = idx % cols

            x = margin_x + col * (label_w + gap_x)
            y = page_h - margin_y - (row + 1) * label_h - row * gap_y

            if show_border:
                c.saveState()
                c.setStrokeColor(colors.HexColor("#D1D5DB"))
                c.setLineWidth(0.6)
                c.setDash(3, 3)
                c.roundRect(x, y, label_w, label_h, 3, stroke=1, fill=0)
                c.restoreState()

            shelf_code = str(item.get("shelf", "")).strip()
            rack_code = str(item.get("rack", "")).strip()

            if not shelf_code:
                continue

            try:
                bw = barcode_scale
                if len(shelf_code) > 10:
                    bw = max(0.85, barcode_scale * (10.0 / len(shelf_code)))

                bc = code128.Code128(
                    shelf_code,
                    barHeight=barcode_height,
                    barWidth=bw,
                    humanReadable=False
                )
                bc_w = bc.width
                bc_x = x + (label_w - bc_w) / 2.0
                if label_h <= 85.0:
                    bc_y = y + 26.0
                    text_y = y + 8.5
                else:
                    bc_y = y + (label_h - barcode_height) / 2.0 + 8.0
                    text_y = y + 20.0

                bc.drawOn(c, bc_x, bc_y)
            except Exception as bc_err:
                print(f"[!] Barcode error: {bc_err}")

            if show_rack and rack_code:
                full_text = f"{shelf_code}-(Rack : {rack_code})"
            else:
                full_text = shelf_code

            c.saveState()
            c.setFont("Helvetica-Bold", font_size)
            c.setFillColor(colors.black)
            text_w = c.stringWidth(full_text, "Helvetica-Bold", font_size)
            text_x = x + (label_w - text_w) / 2.0

            c.drawString(text_x, text_y, full_text)
            c.setStrokeColor(colors.black)
            c.setLineWidth(1.0)
            c.line(text_x, text_y - 2.0, text_x + text_w, text_y - 2.0)
            c.restoreState()

        c.showPage()

    c.save()
    return buf.getvalue()
